CREATE TABLE contacts(
    id INT GENERATED BY DEFAULT AS IDENTITY,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    email VARCHAR(255) NOT NULL,
    phone VARCHAR(15),
    PRIMARY KEY (id)
);
/*NULL = NULL sempre dá falso, 
logo valor = NULL sempre dá uma 
busca em falso.

Para resolver esse tipo de problema,
utiliza-se IS NULL para buscar elementos
iguais a NULL na tabela.*/
INSERT INTO contacts(first_name, last_name, email, phone)
VALUES ('John','Doe','john.doe@example.com',NULL),
    ('Lily','Bush','lily.bush@example.com','(408-234-2764)');
SELECT 
    id, 
    first_name, 
    last_name, 
    email, 
    phone 
FROM  
    contacts
WHERE
    phone IS NULL
ORDER BY
    first_name;

DROP TABLE contacts;